DROP TABLE IF EXISTS FILE_SYSTEM;
CREATE TABLE FILE_SYSTEM
(
  ID VARCHAR(40) NOT NULL COMMENT '主键ID',
  NAME VARCHAR(50) NULL DEFAULT NULL COMMENT '名称',
  USER_ID VARCHAR(40) NULL DEFAULT NULL COMMENT '用户ID',
  PARENT_ID VARCHAR(40) NULL DEFAULT NULL COMMENT '父及ID',
  PATH VARCHAR(200) NULL DEFAULT NULL COMMENT '路径',
  CREATE_DATE DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  TYPE TINYINT(1) NULL DEFAULT NULL COMMENT '类型',
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS ANALYSIS_TASK;
CREATE TABLE ANALYSIS_TASK
(
  ID VARCHAR(40) NOT NULL COMMENT '主键ID',
  NAME VARCHAR(50) NULL DEFAULT NULL COMMENT '名称',
  USER_ID VARCHAR(40) NULL DEFAULT NULL COMMENT '用户ID',
  FILE_ID VARCHAR(40) NULL DEFAULT NULL COMMENT '分析的文件ID',
  PARAM VARCHAR(500) NULL DEFAULT NULL COMMENT '参数',
  OUTPUT_PATH VARCHAR(200) NULL DEFAULT NULL COMMENT '路径',
  CREATE_DATE DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (ID)
);
