DROP TABLE IF EXISTS USERS_INFO;
CREATE TABLE USERS_INFO
(
   ID VARCHAR(40) NOT NULL COMMENT '主键ID',
  `NAME` VARCHAR(64) NOT NULL COMMENT '用户名',
  `SEX` TINYINT(4) DEFAULT '0' COMMENT '性别',
  `AVATAR` VARCHAR(128) DEFAULT NULL COMMENT '头像',
  `EMAIL` VARCHAR(64) DEFAULT NULL COMMENT '邮箱',
  `MOBILE` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '手机',
  `PASSWORD` VARCHAR(128)  NOT NULL DEFAULT '' COMMENT '密码',
  `SALT` VARCHAR(128)  NOT NULL DEFAULT '' COMMENT '盐',
  `STATUS` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '状态,1正常，2禁用',
  `SOURCE` VARCHAR(32)  NOT NULL DEFAULT '' COMMENT '来源',
  `CREATE_ID` INT(11) NOT NULL DEFAULT '0',
  `CREATE_TIME` DATETIME,
  `UPDATE_ID` INT(11) NOT NULL DEFAULT '0',
  `UPDATE_TIME` DATETIME,
  `DELETED` TINYINT(4) NOT NULL DEFAULT '0',
  `ROLE` TINYINT(4) DEFAULT '0',
  `OPEN_ID` VARCHAR(128)  NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`)
);


DROP TABLE IF EXISTS FILE_SYSTEM;
CREATE TABLE FILE_SYSTEM
(
  ID VARCHAR(40) NOT NULL COMMENT '主键ID',
  NAME VARCHAR(50) NULL DEFAULT NULL COMMENT '名称',
  USER_ID VARCHAR(40) NULL DEFAULT NULL COMMENT '用户ID',
  PARENT_ID VARCHAR(40) NULL DEFAULT NULL COMMENT '父及ID',
  PATH VARCHAR(200) NULL DEFAULT NULL COMMENT '路径',
  CREATE_DATE DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  TYPE TINYINT(1) NULL DEFAULT NULL COMMENT '类型',
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS ANALYSIS_TASK;
CREATE TABLE ANALYSIS_TASK
(
  ID VARCHAR(40) NOT NULL COMMENT '主键ID',
  NAME VARCHAR(50) NULL DEFAULT NULL COMMENT '名称',
  USER_ID VARCHAR(40) NULL DEFAULT NULL COMMENT '用户ID',
  FILE_ID VARCHAR(40) NULL DEFAULT NULL COMMENT '分析的文件ID',
  PARAM VARCHAR(500) NULL DEFAULT NULL COMMENT '参数',
  OUTPUT_PATH VARCHAR(200) NULL DEFAULT NULL COMMENT '路径',
  CREATE_DATE DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (ID)
);
