server:
  port: 8888
image:
  analysis:
    cloud:
      app:
        rscript: C:\Users\xinrui\IdeaProjects\image-analysis-app\package-content\R\bin\Rscript
        available-port: false
logging:
  config: classpath:logback-dev.xml
