web:
  file-root: /Users/zhangkai/tmp
  analysis-platform:
    rscript-dir: /Users/zhangkai/IdeaProjects/picture-analysis-admin/R
spring:
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      mode: always


image:
  analysis:
    cloud:
      app:
        rscript: inner
        available-port: true


